FROM node:20.11.1-alpine3.19 AS build

WORKDIR /web
COPY package.json ./
RUN npm install vite --global
RUN yarn install
ENV PATH /web/node_modules/.bin:$PATH
COPY . .
ENTRYPOINT ["yarn", "run", "dev"]